spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          clone-on-start: true

server:
  port: 8888
